services:

  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/flask-app:latest
    container_name: flask-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    volumes:
      - ./website:/app

networks:
  proxy:
    external: true
