services:

  web:
    image: ghcr.io/Stephen-Steyaert-ODU/cs-410-11:latest
    container_name: flask-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    volumes:
      - ./website:/app

networks:
  proxy:
    external: true
